### ISSUE TITLE
Create a json version of dashboard-results

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/obo-dash.github.io#16]
In order for James S. to do his work on the website, we need a stable JSON version of overall results file which is currently YAML.

This is the command to do this with yq

```
yq eval -o=json dashboard/dashboard-results.yml > dashboard/dashboard-results.json
```

But you can also just cycle it through the JSON module when writing the file as part of the framework.

Would you be able to do that @anitacaron?

_Originally posted by @anitacaron in https://github.com/OBOFoundry/obo-dash.github.io/issues/15#issuecomment-2009175153_

**Comment by anitacaron** [comment]
It may need to be part of the framework. `yq` is not available in the ODK.

**Comment by matentzn** [comment]
We could add it: https://github.com/INCATools/ontology-development-kit/issues/838

Or dump it [here](https://github.com/OBOFoundry/OBO-Dashboard/blob/0af8ac6da43e6607c9a1eecb52a820d00438abca/util/dashboard_config.py#L457) like:


```
json_string = json.dumps(json_data)
    with open(filepath, "w") as text_file:
        print(json_string, file=text_file)
```

perhaps. Not sure whats best

**Comment by anitacaron** [comment]
The second option is the fastest way to have the file.

**Comment by jsstevenson** [comment]
@anitacaron @matentzn I noticed yesterday that the dashboard JSON produced [here](https://github.com/OBOFoundry/obo-dash.github.io/blob/6855da4adc2a85ad1a6d9e88c3cc6a6ab9433ee9/dashboard/dashboard-results.json) is now out of date, so I took a very initial stab at a durable fix in the PR above. I'd agree with @anitacaron that dumping the JSON within Python would be much more straightforward and portable -- just make sure to pass an extra handler function to properly serialize datetimes, because they're a full type in YAML but not in JSON (need to be converted to strings somehow eg with `isoformat()`)

**Comment by anitacaron** [comment]
Done in PR https://github.com/OBOFoundry/OBO-Dashboard/pull/114
